// Declare arrays that will store both guessed and generated numbers
let userNumbers = [];
let generatedNum = [];

function getNumbers() {
	// get guessed numbers from user input
	let userNum1 = document.getElementById("number1").valueAsNumber;
	let userNum2 = document.getElementById("number2").valueAsNumber;
	let userNum3 = document.getElementById("number3").valueAsNumber;
	let userNum4 = document.getElementById("number4").valueAsNumber;
	let userNum5 = document.getElementById("number5").valueAsNumber;
	userNumbers.push(userNum1, userNum2, userNum3, userNum4, userNum5);
	
	let lotoNumbers = document.getElementById("generated");	
	// get numbers generated by computer using Math random method
	for (let i = 0; i < 5; i++) {
		let randomNum = Math.floor(Math.random() * 20) + 1;
		generatedNum.push(randomNum);
		
		//display computer generated numbers in the page
	    lotoNumbers.innerHTML = "Computer numbers : " + generatedNum.join(', ') + "<br>";
    }
	//display user guessed numbers in the page
	lotoNumbers.innerHTML += "User numbers : " + userNumbers.join(', ') + "<br>";
	
	getEquals(generatedNum, userNumbers);
}

function getEquals(generatedNum, userNumbers) {
	let newArr = [];
    let match = document.getElementById("difference");	
	
	// get equal elements from two arrays using filter method
	let array = generatedNum.filter(x => userNumbers.indexOf(x) !== -1);
	
	// remove duplicate from array
	for (let i of array) {
     	if (newArr.indexOf(i) === -1) {
		    newArr.push(i);
		}
	}

	// display the matching numbers in the page
    match.innerHTML ="Matching number(s) : " + newArr.join(', ') + "<br>";
	
	if (newArr.length === 1) {
		match.innerHTML +="You win 10 pts";
	}
	else if (newArr.length === 2) {
		match.innerHTML +="You win 100 pts";
	}
	else if (newArr.length === 3) {
		match.innerHTML +="You win 1000 pts";
	}
	else if (newArr.length === 4) {
		match.innerHTML +="You win 5000 pts";
	}
	else if (newArr.length === 5) {
		match.innerHTML +="You win 10000 pts";
	}
	else  {
		match.innerHTML +="You don't win nothing";
	}
	display.disabled = true;
}

// function to reset the game 
function resetDoc() {
	document.getElementById("number1").innerHTML = " ";
	document.getElementById("number2").innerHTML = " ";
	document.getElementById("number3").innerHTML = " ";
	document.getElementById("number4").innerHTML = " ";
	document.getElementById("number5").innerHTML = " ";
	document.getElementById("generated").innerHTML = " ";
    document.getElementById("difference").innerHTML = " ";
	location.reload();
	return false;
}

// function that determine the current year
function updateYear() {
	var now = new Date();
	var theYear = now.getFullYear();
	var thisYear = document.getElementById("ye");
	thisYear.innerHTML = theYear;
	return theYear;
}

function createEventListeners() {
	updateYear();
	let display = document.getElementById("display");
	display.addEventListener("click", getNumbers, false);
	let newDoc = document.getElementById("reset");
	newDoc.addEventListener("click", resetDoc, false);
	document.getElementById("number1").focus();
}

window.addEventListener("load", createEventListeners, false);	
